sudo: required
dist: trusty
language: ruby

cache:
    pip: true
    apt: true

rvm: 2.3

env:
  global:
    - CI_RUN=1
    - ODOO_HELPER_INSTALL_PATH=$TRAVIS_BUILD_DIR

install:
  - "gem install bashcov:1.5.1 coveralls:0.8.13 codecov"
  - "bash install-user.bash"

script:
  - "bashcov tests/test.bash"
