sudo: required
language: bash

env:
  global:
    - CI_RUN=1

install:
  - "bash install-user.bash"
  - "cat $HOME/.profile"
  - "ls -l --color ./bin"
  - "env"
  - "bash -c 'env'"
  - "command -v odoo-install; true"

script:
  - "source ~/.profile && bash test.bash"

