sudo: required
dist: trusty
language: ruby

cache:
    pip: true
    apt: true

rvm: 2.3

env:
  global:
    - CI_RUN=1
    - ODOO_HELPER_INSTALL_PATH=$TRAVIS_BUILD_DIR
    - TEST_TMP_DIR=/tmp/odoo-helper-tests

install:
  - "gem install bashcov codecov"
  - "bash install-user.bash"

script:
  - "bashcov tests/test.bash"
