sudo: required
dist: trusty
language: ruby

cache:
    pip: true
    apt: true

rvm: 2.3

env:
  global:
    - CI_RUN=1
    - ODOO_HELPER_ROOT=$TRAVIS_BUILD_DIR

install:
  - "sudo apt-get install -y -qq git python-all-dev libevent-dev expect-dev libxml2-dev"
  - "gem install bashcov coveralls"
  - "bash install-user.bash"

script:
  - "bashcov tests/test.bash"


after_success:
  - coveralls

